HTTP/1.1 200 OK
Server: gunicorn/19.3.0
Date: %% '.*' %%
Connection: close
Content-Type: application/json
Content-Length: 248
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {
    "foo": "bar", 
    "lol": "beans"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Host": "localhost:8000", 
    "User-Agent": "curl/7.50.1"
  }, 
  "origin": "%% '[0-9.]\+' %%", 
  "url": "http://localhost:8000/get?foo=bar&lol=beans"
}
