HTTP/1.1 302 FOUND
Server: gunicorn/%% '.*' %%
Date: %% '.*' %%
Connection: close
Content-Type: text/html; charset=utf-8
Content-Length: 0
Location: http://localhost:8000/get
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

HTTP/1.1 200 OK
Server: gunicorn/%% '.*' %%
Date: %% '.*' %%
Connection: close
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Length: %% '[0-9]\+' %%

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "localhost:8000", 
    "User-Agent": "curl/%% '.*' %%"
  }, 
  "origin": "%% '[0-9.]\+' %%", 
  "url": "http://localhost:8000/get"
}
