HTTP/1.1 200 OK
Server: gunicorn/%% '.*' %%
Date: %% '.*' %%
Connection: close
Content-Type: application/json
Content-Length: 189
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "localhost:8000", 
    "User-Agent": "curl/7.50.1"
  }, 
  "origin": "%% '[0-9.]\+' %%", 
  "url": "http://localhost:8000/get"
}
